bootstrap: add missing 'return False'  in is_running()
bluerobotics/BlueOS pull request #1873
Opened 2023-07-13 20:00 UTC by Williangalvani

not tested yet, but a docker is up at  williangalvani/blueos-bootstrap:addreturn

2023-07-13 20:03 UTC, patrickelectric approved these changes

2023-07-14 18:04 UTC, Williangalvani commented on bootstrap/test_bootstrap.py
> -        assert bootstrapper.is_running("core")
this line should not have been removed

2023-07-14 18:23 UTC, Williangalvani commented on bootstrap/test_bootstrap.py
> -        assert bootstrapper.is_running("core")
nevermind, I read the patch wrong =|

2023-07-14 19:49 UTC, patrickelectric requested changes
It's restarting core every 12s
![image](https://github.com/bluerobotics/BlueOS/assets/1215497/4346f478-9402-453b-ace5-33b55cdcc643)

2023-07-17 12:06 UTC, patrickelectric approved these changes
After further testing I got it working, it was a problem with my binds

2023-07-17 12:06 UTC, merged

2023-07-17 12:33 UTC, Williangalvani commented
I am actually not so sure. I'll add a test for the timeout in another pr just to be sure