core: frontend: components: AutopilotManagerUpdater: Add restart function
bluerobotics/BlueOS pull request #2063
Opened 2023-08-28 16:37 UTC by patrickelectric

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2023-08-28 17:10 UTC, Williangalvani requested changes
nice, I was just thinking about where to place it. this looks good

found a typo though

2023-08-28 17:10 UTC, Williangalvani commented on core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> +import * as AutopitlotManager from '@/components/autopilot/AutopilotManagerUpdater'
AutopitlotManager

2023-09-04 19:04 UTC, patrickelectric commented
ping @Williangalvani @joaoantoniocardoso @rafaellehmkuhl

2023-09-04 21:43 UTC, joaoantoniocardoso approved these changes
Good one, tested :)

2023-09-04 22:22 UTC, merged