Move frontend to use bun and vite
bluerobotics/BlueOS pull request #2111
Opened 2023-09-15 07:20 UTC by patrickelectric

frontend build + install + lint is now 2.5x faster [155s vs 61s]
frontend test server (moved from `yarn server` to `bun run vite`) is now 5x faster [39s vs 8s]

Vite is the same build tool used in cockpit, and bun.. bun is the future.
![image](https://github.com/bluerobotics/BlueOS/assets/1215497/eab6aa36-3224-41e3-9bcb-92d2b1478a35)

2023-09-15 14:17 UTC, Williangalvani commented
I ran into this issue:

```
  VITE v3.2.7  ready in 303 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
The following dependencies are imported but could not be resolved:

  vue-router/types/router (imported by /home/will/git/blueos/blueos-docker/core/frontend/src/components/wizard/DefaultParamLoader.vue?id=0)

Are they installed?
```

2023-09-15 14:19 UTC, patrickelectric commented
> I ran into this issue:
> 
> ```
>   VITE v3.2.7  ready in 303 ms
> 
>   ➜  Local:   http://localhost:5173/
>   ➜  Network: use --host to expose
> The following dependencies are imported but could not be resolved:
> 
>   vue-router/types/router (imported by /home/will/git/blueos/blueos-docker/core/frontend/src/components/wizard/DefaultParamLoader.vue?id=0)
> 
> Are they installed?
> ```

Does it affect it somehow ? I saw no problems since its related to the type system.

2023-09-15 14:30 UTC, Williangalvani commented
> Does it affect it somehow ? I saw no problems since its related to the type system.

hah, it is actually running, the hanging output made me think it was hanging. fair enough


I'm having some issues with proxying. version-chooser, vehicle setup, and the mavlink websocket seem to be affected

2023-09-15 14:42 UTC, patrickelectric commented
> > Does it affect it somehow ? I saw no problems since its related to the type system.
> 
> hah, it is actually running, the hanging output made me think it was hanging. fair enough
> 
> I'm having some issues with proxying. version-chooser, vehicle setup, and the mavlink websocket seem to be affected

That's probably the websocket proxy, will take a look.

2023-09-16 01:03 UTC, joaoantoniocardoso requested changes
Couldn't make it work here.
What I've tried:
```
bun build
bun vite serve
bun vite serve --host
```

In either case, it says:

> (!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

Also:
* it creates a file called `core/frontend/components.d.ts`, which IDKN if we want to commit or ignore.
* it creates a file called `core/frontend/bun.lockb`, which we probably want to ignore.

2023-09-16 01:05 UTC, joaoantoniocardoso commented
Oh, now I noticed, it should be `bun vite run` :facepalm: .

It loaded after some (5?) seconds:
```
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/img/blueos-logo-blue.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-blue.svg instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/img/blueos-logo-white.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-white.svg instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/boat/UNDEFINED.glb, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/boat/UNDEFINED.json, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/rover/unknown.glb, put the file in the src directory, and use /src/assets/vehicles/models/rover/unknown.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/BLUEROV1.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/BLUEROV1.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/SIMPLEROV_5.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_5.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/VECTORED.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/VECTORED_6DOF.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED_6DOF.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/VECTORED_6DOF.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED_6DOF.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/bluerov.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/bluerov.glb instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/vehicles/models/sub/VECTORED.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED.json instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/img/devicePathHelper/navigator.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/navigator.svg instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/img/devicePathHelper/rpi3b.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/rpi3b.svg instead.
Assets in public cannot be imported from JavaScript.
Instead of /public/assets/img/devicePathHelper/rpi4b.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/rpi4b.svg instead.

PWA v0.16.5
mode      generateSW
precache  1 entries (0.00 KiB)
files generated
  dev-dist/sw.js
  dev-dist/workbox-fa446783.js
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/home/joaoantoniocardoso/BlueRobotics/BlueOS-docker/core/frontend/dev-dist",
  "globPattern": "**/*.{js,css,html}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}
```

2023-09-16 01:27 UTC, patrickelectric commented
> Oh, now I noticed it should be `bun vite run` 🤦 .
> 
> It loaded after some (5?) seconds:
> 
> ```
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/blueos-logo-blue.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-blue.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/blueos-logo-white.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-white.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/boat/UNDEFINED.glb, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/boat/UNDEFINED.json, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/rover/unknown.glb, put the file in the src directory, and use /src/assets/vehicles/models/rover/unknown.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/BLUEROV1.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/BLUEROV1.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_5.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_5.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/VECTORED.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/VECTORED_6DOF.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED_6DOF.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/VECTORED_6DOF.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED_6DOF.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/bluerov.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/bluerov.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/VECTORED.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/VECTORED.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/devicePathHelper/navigator.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/navigator.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/devicePathHelper/rpi3b.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/rpi3b.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/devicePathHelper/rpi4b.svg, put the file in the src directory, and use /src/assets/img/devicePathHelper/rpi4b.svg instead.
> 
> PWA v0.16.5
> mode      generateSW
> precache  1 entries (0.00 KiB)
> files generated
>   dev-dist/sw.js
>   dev-dist/workbox-fa446783.js
> warnings
>   One of the glob patterns doesn't match any files. Please remove or fix the following: {
>   "globDirectory": "/home/joaoantoniocardoso/BlueRobotics/BlueOS-docker/core/frontend/dev-dist",
>   "globPattern": "**/*.{js,css,html}",
>   "globIgnores": [
>     "**/node_modules/**/*",
>     "sw.js",
>     "workbox-*.js"
>   ]
> }
> 
> files in the public directory are served at the root path.
> Instead of /public/assets/img/blueos-logo-white.svg, use /assets/img/blueos-logo-white.svg.
> ```
> 
> ![image](https://user-images.githubusercontent.com/5920286/268418904-41118261-76c2-419e-8596-94f033fc0182.png)
> 
> When I tried to load an extension:
> 
> ```
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/blueos-logo-blue.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-blue.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/img/blueos-logo-white.svg, put the file in the src directory, and use /src/assets/img/blueos-logo-white.svg instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/boat/UNDEFINED.glb, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/boat/UNDEFINED.json, put the file in the src directory, and use /src/assets/vehicles/models/boat/UNDEFINED.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/rover/unknown.glb, put the file in the src directory, and use /src/assets/vehicles/models/rover/unknown.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/BLUEROV1.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/BLUEROV1.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/BLUEROV1.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_3.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_3.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_4.json, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_4.json instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/SIMPLEROV_5.glb, put the file in the src directory, and use /src/assets/vehicles/models/sub/SIMPLEROV_5.glb instead.
> Assets in public cannot be imported from JavaScript.
> Instead of /public/assets/vehicles/models/sub/VECTORED.glb, put the file in the src directory, and use /src/assets/vehicles/mode [...]

2023-09-16 01:47 UTC, joaoantoniocardoso commented
> But did it affect something? That's a result of how we include such files. It's just a warning but everything should work. We can improve it in future PRs.

I believe so, the image I posted seems to be missing the other vehicle avatars.

Despite that, there are connection issues, should I test it with that same environment variable to set the IP?

2023-09-20 02:31 UTC, joaoantoniocardoso commented on core/frontend/.gitignore
> +bun.lockb
```suggestion
dev-dist/
bun.lockb
components.d.ts
```

2023-09-20 02:42 UTC, joaoantoniocardoso commented on core/frontend/yarn.lock
We should keep it for compatibility. Since the bun lock file is binary, there's no good way to see what should be the package versions.

2023-09-20 02:43 UTC, joaoantoniocardoso reviewed
Tested:
* yarn still works
* everything seems to be working, except vehicle images (see #2116)

2023-09-20 02:43 UTC, joaoantoniocardoso approved these changes
=)

2023-09-21 14:07 UTC, merged