core: services: kraken: Add size of extension
bluerobotics/BlueOS pull request #2124
Opened 2023-09-21 18:13 UTC by patrickelectric

![image](https://github.com/bluerobotics/BlueOS/assets/1215497/a079bfc5-ce0a-4290-b4b8-8787df765959)
ps: Yes, it's a 128GB sdcard

2023-09-25 19:58 UTC, patrickelectric commented
ping @joaoantoniocardoso @Williangalvani

2023-09-26 14:29 UTC, Williangalvani requested changes
it misbehaved a couple of times here, where it only loaded stats for some of the containers, but I don't think it is related to this pr.

Other than that print, it looks great

2023-09-26 14:29 UTC, Williangalvani commented on core/services/kraken/kraken.py
> +                print(show)
```suggestion
```
debugging code

2023-09-27 17:05 UTC, joaoantoniocardoso approved these changes

2023-09-28 19:56 UTC, Williangalvani requested changes
sorry, minor typing issue

2023-09-28 19:56 UTC, Williangalvani commented on core/frontend/src/components/kraken/InstalledExtensionCard.vue
> +    },
My brain is not working well today. but the typing here looks wrong.

if `main_disk()` is a number, how can we access `total_space_B` of it in the second method?

And why is CI not catching this?

2023-12-05 16:11 UTC, patrickelectric commented
ping @Williangalvani

2023-12-05 16:34 UTC, merged