[Feature] - Add BlueOS specific custom aliases [WIP]
bluerobotics/BlueOS pull request #2239
Opened 2023-12-08 13:03 UTC by RaulTrombin

The main idea is to have BlueOS focused aliases:
In this PR specifically it only adds a warn script when user try apt-get upgrade, this solves:[kernel upgrade issue](https://github.com/bluerobotics/BlueOS/issues/2234
)

But it can be expanded for BlueOS focused commands, such : 
- reset BlueOS services - restart containers if only have access from shell;
- use factory recovery - stops actual container and return factory;
- reset stable BlueOS kernel

2023-12-08 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=2239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=2239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bluerobotics/BlueOS?pullRequest=2239) it.</sub>

2023-12-08 15:19 UTC, patrickelectric requested changes

2023-12-08 16:07 UTC, RaulTrombin commented
Thks for inputs, I've updated the requirements for this feature on description, 
Some howto implement this should be discussed, please fell free to update description and ideas.
Aparently a better aproach will be to use blueos-core container instead bootstrap and .profile;
@patrickelectric @joaoantoniocardoso

2023-12-08 16:57 UTC, joaoantoniocardoso commented on core/tools/blueos_startup_update/blueos_startup_update
> +    target_string = '''# BlueOS Aliases Starter\nif [ -f ~/.bash_aliases ]; then\n. ~/.bash_aliases_blueos\nfi'''
use `/etc/bashrc` instead, it's the system-wide one

2023-12-08 16:59 UTC, joaoantoniocardoso commented on core/tools/blueos_startup_update/blueos_startup_update
> +    target_string = '''# BlueOS Aliases Starter\nif [ -f ~/.bash_aliases ]; then\n. ~/.bash_aliases_blueos\nfi'''
note that then, the `bash_aliases` file should live in a public place

2026-09-11 18:01 UTC, patrickelectric commented
two years without updates. be free to reopen if you are going to continue the work.

2026-09-11 18:01 UTC, closed without merging