Scripts on Wizard
bluerobotics/BlueOS pull request #2487
Opened 2024-03-25 23:20 UTC by Williangalvani

Needs more testing, but looking good so far. I'll review it tomorrow

2024-03-25 23:22 UTC, Williangalvani commented
depends on https://github.com/bluerobotics/Blueos-Parameter-Repository/pull/6

2024-03-25 23:22 UTC, Williangalvani commented on core/frontend/src/components/wizard/ScriptLoader.vue
> +const REPOSITORY_ROOT = 'https://williangalvani.github.io/Blueos-Parameter-Repository_/'
update after https://github.com/bluerobotics/Blueos-Parameter-Repository/pull/6

2024-03-25 23:23 UTC, Williangalvani commented on core/frontend/src/components/wizard/Wizard.vue
> +const REPOSITORY_ROOT = 'https://williangalvani.github.io/Blueos-Parameter-Repository_/'
update after https://github.com/bluerobotics/Blueos-Parameter-Repository/pull/6

2024-03-26 11:55 UTC, patrickelectric requested changes

2024-03-26 14:37 UTC, Williangalvani commented on core/frontend/src/components/wizard/Wizard.vue
> +      await filebrowser.createFolder('')
yep, this is wrong

2024-03-26 15:11 UTC, Williangalvani commented on core/frontend/src/components/wizard/Wizard.vue
> +      await filebrowser.createFolder('')
the upside is we found out we don't need to explicitly create the folder

2024-03-26 19:42 UTC, patrickelectric approved these changes

2024-03-26 19:42 UTC, merged

2024-03-26 19:43 UTC, patrickelectric commented
@Williangalvani can you cherry-pick to 1.2 ?