Kraken: Add Manifest V2 with multiple manifest support
bluerobotics/BlueOS pull request #2607
Opened 2024-05-20 14:41 UTC by JoaoMario109

Depends on #2604

2024-05-24 03:11 UTC, Williangalvani requested changes
This is looking very good!

I have 3 comments though:
 - Can we show on the list if a manifest is disabled? currently we need to click the edit button.
 - Can we decrease the timeouts? 20s is a LONG time for waiting before giving the user some feedback, specially on post/delete.
 - we should add some url validation in the form, just in case. (I added gibberish and it gave me an internal error)

2024-05-28 18:12 UTC, patrickelectric approved these changes

2024-05-28 18:13 UTC, patrickelectric requested changes
ops, wrong button

2024-05-29 10:26 UTC, patrickelectric commented on core/frontend/src/components/kraken/ExtensionSettings.vue
> +      this.operation_open = this.is_operation_url_invalid || false
This is not possible since previous functions modify the internal variables that will affect updateSource

2024-05-29 10:27 UTC, patrickelectric commented on core/frontend/src/components/kraken/ExtensionSettings.vue
> +      const parts = cut_path.split('/').filter((part) => !part.endsWith('.json') && !part.endsWith('.txt'))
The current logic is good enough for what we want, there is tradeoffs, but it should be not an issue for an automatic name generation method.

2024-05-29 10:43 UTC, JoaoMario109 commented on core/frontend/src/components/kraken/ExtensionSettings.vue
> +      if (cut_path === '') {
Fixed!

2024-05-29 10:43 UTC, JoaoMario109 commented on core/frontend/src/components/kraken/ExtensionSettings.vue
> +          url: `${KRAKEN_API_V2_URL}/manifest/?validate_url=${!this.should_bypass_validate}`,
Moved to a dedicated kraken API wrapper file.

2024-05-29 11:53 UTC, patrickelectric approved these changes

2024-05-29 11:54 UTC, patrickelectric commented
It'll be merged once the change request from @Williangalvani get solved. (Needs approval)

2024-05-29 19:31 UTC, Williangalvani approved these changes

2024-05-29 19:31 UTC, merged