Add TLS support
bluerobotics/BlueOS pull request #2697
Opened 2024-06-16 20:19 UTC by matt-bathyscope

This PR adds support for TLS in nginx using a self-signed certificate that's unique to each robot, along with additional changes needed for other components to work when TLS is enabled.

- Moves the nginx config to `/etc/blueos/nginx/` instead of the current tools path in the container so we have persistence.
- Updates the bootstrap container's version-chooser reachability check to accept the self-signed cert so it doesn't kill the core container.
- Adds a checkbox to the vehicle configuration wizard to enable the TLS feature.
- Generates a certificate (when needed) that includes the alternate hostname(s) and IPs for the robot. This feature shells out to `openssl` to do the crypto operations, but attempts to mitigate any command injection risk by escaping parameters (like hostname) with the `shlex.quote` function. The cert and key files are stored alongside the nginx config.
- There are two "template" nginx configs, one with TLS and one without, that are shipped with the `core`. The code moves the correct one into place depending on whether or not TLS should be enabled.

### How to test this

1. Manually choose the TLS-aware bootstrap and core images from CI (or from the correct tag on DockerHub)
2. Re-run the vehicle setup wizard
3. Check the `Enable TLS` box on the `Customize` step
![Screenshot 2024-06-16 at 13 09 11](https://github.com/bluerobotics/BlueOS/assets/54611367/65b1a15b-3983-41b3-8cb0-bc14caad24f7)
4. Complete the wizard
![Screenshot 2024-06-16 at 13 09 26](https://github.com/bluerobotics/BlueOS/assets/54611367/8aed26c8-566c-4c05-8b6b-86cb11eeb75f)
5. Navigate to `https://<your robot hostname>`
6. Accept the cert warning
7. You should have TLS now

2024-06-16 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=2697) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=2697) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bluerobotics/BlueOS?pullRequest=2697) it.</sub>

2024-06-16 21:09 UTC, patrickelectric requested changes
I'll check it more deeply during the week

2024-06-18 18:49 UTC, matt-bathyscope commented on core/services/beacon/main.py
> +        alt_names.append("IP:192.168.2.2")
Resolved with [53fff46](https://github.com/bluerobotics/BlueOS/pull/2697/commits/53fff462964a9de928409a3ab878f48f458cc886)

2024-06-18 18:49 UTC, matt-bathyscope commented on core/frontend/src/components/wizard/Wizard.vue
> +        .catch(() => 'False to change TLS configuration')
Resolved with [7764b7c](https://github.com/bluerobotics/BlueOS/pull/2697/commits/7764b7cb5693f300fc2ff8540dc8bd90d05f2ee7)

2024-07-02 13:35 UTC, patrickelectric commented
Hi @matt-bathyscope can you sign the CLA ?

2025-06-20 22:31 UTC, matt-bathyscope commented
Closing this one as there is an updated/rebased PR https://github.com/bluerobotics/BlueOS/pull/3389

2025-06-20 22:31 UTC, closed without merging