CoC: Add first commit
bluerobotics/BlueOS pull request #2715
Opened 2024-06-20 16:19 UTC by patrickelectric

2024-06-20 16:26 UTC, joaoantoniocardoso approved these changes

2024-06-20 16:35 UTC, rafaellehmkuhl commented
A 5a serie...

2024-06-21 11:31 UTC, ES-Alexander requested changes
Mostly looks good. A few minor suggestions :-)

2024-06-21 11:31 UTC, ES-Alexander commented on CoC.md
> +BlueOS, maintainers, project participants, and contributors (collectively, “participants”) are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and
```suggestion
BlueOS maintainers, project participants, and contributors (collectively, “participants”) are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.
```

2024-06-21 11:31 UTC, ES-Alexander commented on CoC.md
> +Blue Robotics has the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban
```suggestion
As the primary project maintainer, Blue Robotics has the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.
```
Seems worth contextualising _why_ we have those rights and responsibilities :-)

2024-06-21 11:31 UTC, ES-Alexander commented on CoC.md
> +> Ref: This CoC is was originaly based on [Dronecode Foundation CoC](https://discuss.px4.io/t/px4-community-code-of-conduct/13655)
```suggestion
> Ref: This CoC is adapted from the [Dronecode Foundation CoC](https://discuss.px4.io/t/px4-community-code-of-conduct/13655)
```

2024-06-22 03:32 UTC, patrickelectric commented
@ES-Alexander check now

2024-06-22 13:49 UTC, ES-Alexander approved these changes
Love it! :-)

2024-06-22 13:49 UTC, merged

2024-07-08 13:55 UTC, ES-Alexander commented
Docs should mention this in the development overview :-)