Add cron worker with journalctl cleaner
bluerobotics/BlueOS pull request #2790
Opened 2024-07-05 18:12 UTC by patrickelectric

Helps #2328

2024-07-05 19:31 UTC, Williangalvani commented
should we use a script instead? we need something to cleanup the autopilot and mavlink logs from time to time, too :thinking:

2024-07-06 01:20 UTC, patrickelectric commented
> should we use a script instead? we need something to cleanup the autopilot and mavlink logs from time to time, too 🤔

what you mean by script ?

2024-07-06 01:38 UTC, Williangalvani commented
> what you mean by script ?

never mind, if we have cron working, we can just had other entries for cleaning different things

2024-07-06 02:18 UTC, patrickelectric commented
> > what you mean by script ?
> 
> never mind, if we have cron working, we can just had other entries for cleaning different things

yes, that the plan

2024-07-08 11:42 UTC, joaoantoniocardoso requested changes
The idea of adding a cron is interesting for our system, however, journalctl is a log manager that doesn't require user intervention: it has configurations like (1) log size, (2) free disk size, (3) rate limit, (4) compression, and it will vacuum automatically.

https://www.freedesktop.org/software/systemd/man/latest/journald.conf.html

2024-07-08 11:48 UTC, patrickelectric commented
What is better, calling journalctl configuration command or working on journalctl configuration file/parameters, dealing with user custom configuration and identifying (based in the OS), which of the following files to change ?
/etc/systemd/journald.conf
/run/systemd/journald.conf
/usr/local/lib/systemd/journald.conf
/usr/lib/systemd/journald.conf
/etc/systemd/journald.conf.d/*.conf
/run/systemd/journald.conf.d/*.conf
/usr/local/lib/systemd/journald.conf.d/*.conf

2024-07-08 11:50 UTC, patrickelectric commented
To me it adds extra complexity at the moment, what is the problem of the current approach ?

2024-07-08 12:13 UTC, joaoantoniocardoso commented
> To me it adds extra complexity at the moment, what is the problem of the current approach ?

(1) we are taking power from the administrator, and (2) we are reinventing the wheel instead of configuring a basic system tool.

What I recommend is that when installing the system, we should overwrite (with a backup) `/etc/systemd/journald.conf`, print a message about it, and if the administrator wants a different configuration from our default, he can just change the configs there after installing it.

2024-07-08 12:40 UTC, patrickelectric commented
> > To me it adds extra complexity at the moment, what is the problem of the current approach ?
> 
> (1) we are taking power from the administrator, and (2) we are reinventing the wheel instead of configuring a basic system tool.
> 
> What I recommend is that when installing the system, we should overwrite (with a backup) `/etc/systemd/journald.conf`, print a message about it, and if the administrator wants a different configuration from our default, he can just change the configs there after installing it.

Installation does not fix the problem for current BlueOS systems.

2024-07-09 12:36 UTC, joaoantoniocardoso commented
> > > To me it adds extra complexity at the moment, what is the problem of the current approach ?
> > 
> > 
> > (1) we are taking power from the administrator, and (2) we are reinventing the wheel instead of configuring a basic system tool.
> > What I recommend is that when installing the system, we should overwrite (with a backup) `/etc/systemd/journald.conf`, print a message about it, and if the administrator wants a different configuration from our default, he can just change the configs there after installing it.
> 
> Installation does not fix the problem for current BlueOS systems.

Can't we install it if the file doesn't exist?

2024-07-09 12:39 UTC, patrickelectric commented
> > > > To me it adds extra complexity at the moment, what is the problem of the current approach ?
> > > 
> > > 
> > > (1) we are taking power from the administrator, and (2) we are reinventing the wheel instead of configuring a basic system tool.
> > > What I recommend is that when installing the system, we should overwrite (with a backup) `/etc/systemd/journald.conf`, print a message about it, and if the administrator wants a different configuration from our default, he can just change the configs there after installing it.
> > 
> > 
> > Installation does not fix the problem for current BlueOS systems.
> 
> Can't we install it if the file doesn't exist?

By default this file comes from the OS.

2024-07-09 12:39 UTC, patrickelectric commented
I'm working in an alternative solution.

2026-09-11 17:59 UTC, patrickelectric commented
Closing: last activity older than a year.

2026-09-11 17:59 UTC, closed without merging