CI: use sanitized platform name for deployment
bluerobotics/BlueOS pull request #2937
Opened 2024-10-01 21:45 UTC by Williangalvani

2024-10-01 22:24 UTC, joaoantoniocardoso commented on .github/workflows/test-and-deploy.yml
> +          zip BlueOS-raspberry-${{ env.SANITIZED_PLATFORM }}-${{ matrix.os }}.zip deploy/pimod/blueos.img
this is defined in the next step

2024-10-01 22:25 UTC, joaoantoniocardoso requested changes
check the steps order

2024-10-01 23:51 UTC, Williangalvani commented on .github/workflows/test-and-deploy.yml
> +          zip BlueOS-raspberry-${{ env.SANITIZED_PLATFORM }}-${{ matrix.os }}.zip deploy/pimod/blueos.img
:man_facepalming:

2024-10-02 01:18 UTC, joaoantoniocardoso approved these changes

2024-10-02 01:19 UTC, merged