added user to docker group
bluerobotics/BlueOS pull request #296
Opened 2021-05-28 18:45 UTC by slayer321

fix #292

2021-05-28 19:55 UTC, rafaellehmkuhl requested changes

2021-05-28 19:55 UTC, rafaellehmkuhl commented on install/install.sh
> +echo "Created the docker group"
"Creating the docker group." seems to replicate better the other messages writing style.

Also, this command is in fact adding the default user to the pre-existing docker group, so something like "Adding default user to 'docker' group." seems better.

2021-05-28 19:55 UTC, rafaellehmkuhl commented on install/install.sh
> +
Better to remove this extra line.

2021-05-28 19:55 UTC, rafaellehmkuhl commented on install/install.sh
> +#creating a Unix group called docker and adding users to it.
Please atent to the space after the `#` and also the message, as the following comment explains.

2021-05-31 22:07 UTC, rafaellehmkuhl requested changes

2021-05-31 22:07 UTC, rafaellehmkuhl commented on install/install.sh
> +# creating a Unix group called docker and adding users to it
This comment also needs to change.
Something like "Add user to 'docker' group allowing docker commands without root privilegies"

2021-10-05 17:09 UTC, rafaellehmkuhl commented
@patrickelectric as I understand the idea is to change from this to using the `pi` user on dockers, right?

2022-10-06 06:00 UTC, ES-Alexander commented
I just came across this PR while looking for something else.

> as I understand the idea is to change from this to using the `pi` user on dockers, right?

@rafaellehmkuhl that could cause issues given we should generally be moving away from `pi` user dependence, per #1073

2023-08-23 17:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=296) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bluerobotics/BlueOS?pullRequest=296) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bluerobotics/BlueOS?pullRequest=296) it.</sub>

2023-08-24 06:19 UTC, slayer321 commented
Hey @rafaellehmkuhl , just wanted to know that is this PR still relevant or we can close it ?

2025-04-15 13:24 UTC, closed without merging

2025-04-15 13:24 UTC, joaoantoniocardoso commented
Thanks for the contribution @slayer321, it ended up being superseded by #2979.